### ISSUE TITLE
Transfer - button to offer NFT as a Gift

### ISSUE THREAD

**Issue by zapaz** [Kredeum/kredeum#127]
Transfert NFT free, as a Gift

**TODO**
1. Add a button to offer NFT as a Gift, opening a form (popup ?)  to enter the destination address
  - Design
  - HTML Integration
  - Svelte Integration
  
**DONE** 
2. SmartContract: free transfer NFT, included in all ERC721 contracts

**Comment by Yoannkrd** [comment]
test

**Comment by zapaz** [comment]
partir de la branche transferNft

**Comment by zapaz** [comment]
Done in PR #102
