### ISSUE TITLE
Video type

### ISSUE THREAD

**Issue by zapaz** [Kredeum/kredeum#128]
Basic : Take into account video (or animation) as NFT type

Advanced : Take into account any content/type : image/* video/* text/* sound/* etc...

** TODO **
- UI / UX : provide HTML viewer for video format  + css classes (media-video and media-image for example)
- UI / UX : provide HTML viewer for other format
- Svelte + JS : detect NFT content/type (unfortunatly not in the metadata)

**Comment by zapaz** [comment]
partir de la branche main

**Comment by Baptiste-krd** [comment]
C'est push ! Je te laisse me dire si ça fonctionne en prod.

**Comment by zapaz** [comment]
thanks !
