### ISSUE TITLE
Add description field to a NFT and symbol field to a collection

### ISSUE THREAD

**Issue by Yoannkrd** [Kredeum/kredeum#137]
Create Collection : add symbol field
Mint NFT : add description field

**Comment by Yoannkrd** [comment]
Partir du main

**Comment by Yoannkrd** [comment]
Vérifier l'usage du champ symbole pour une collection

**Comment by zapaz** [comment]
En option ajouter un champ optionnel : prix (fixe) de vente en direct (sans passer par OpenSea)

**Comment by Yoannkrd** [comment]
Hello Baptiste
J'ai créé la branche 137.
J'ai ajouté dans maq.html une section contenant une input type textarea.
Le champ input textaera n'est stylé, peux tu t'en charger?
Merci
Yoann

**Comment by Yoannkrd** [comment]
@zapaz pour info:
- Champ symbole intégré dans la création des collections
- Champ description ajouté à la création des NFTs (pour l'instant uniquement type text)

**Comment by zapaz** [comment]
done
