### ISSUE TITLE
Popup not showing

### ISSUE THREAD

**Issue by zapaz** [Kredeum/kredeum#144]
@Guido on Discord "If have connected my metamask wallet to my wordpress but the pop up for the transaction is not showing"

![unknown](https://user-images.githubusercontent.com/4560471/151007350-94311766-6de3-4d01-94ba-db96bbc00a54.png)

![unknown](https://user-images.githubusercontent.com/4560471/151006727-11587511-cf93-4c6f-b4ed-0416e42502b3.png)

**Comment by Guidovangelder** [comment]
Any update on the error?

**Comment by zapaz** [comment]
> Any update on the error?

Humm, difficult to investigate... you changed network 2 times, may be this cause the error ?


What you should do : 
1/ upgrade to the latest version v0.9.17 , that includes a fix 
2/ refresh your browser on the targeted network, and do not change network while creating collection or minting
(as some bugs may be due to network switching)

**Comment by Guidovangelder** [comment]
On polygon network the plugin is working. But not on the ETH network
![image](https://user-images.githubusercontent.com/47634757/151014410-0f698e5e-c536-48a4-ba6c-ac4da34d16c7.png)

**Comment by zapaz** [comment]
yes, Mainnet NFT template is different (older version) than the template on Polygon... 
we update template more slowly on mainnet, as you may understand... 

but still continuing to investing on this backward compatibility issue

**Comment by zapaz** [comment]
This compatibility issue has been fixed, you can check on alpha release => https://alpha.kredeum.com

This alpha is not stable, so you have to wait before getting into beta version
