### ISSUE TITLE
Displayer component for different media types

### ISSUE THREAD

**Issue by dlaxcess** [Kredeum/kredeum#182]
Create a general Component to display all different Média types.
The component will take parameters to chose how it have to be displayed : 
- In the grid
- In Nft solo Page
- In list line
- with or without preview/zoom modale
- (...)

The logic inside will reconize with type of média to display
- Image
- Vidéo
- Audio
- (...)

To display the media, the component will use other specifics componants depending of the use case 

The purpose is to make independent components wich will be ables to work the same in all projects.
To do that, we'll have to integer SCSS styles inside each component and take it out of the generals SCSS styles as often as it's possible.
We'll have to integer in component's styles some SCSS variables that can be imported depending of the project (colors, ...)
we'll probablly have to integer "generals styles" in top levels component of the média displayer component.
(Doc about this=> https://github.com/sveltejs/svelte-preprocess )

N.B : Will have to discuss all together about this last point of integering SCSS styles in components

**Comment by zapaz** [comment]
done
