### ISSUE TITLE
7 - Refresh collections metadata on wordpress

### ISSUE THREAD

**Issue by dlaxcess** [Kredeum/kredeum#245]
## Objective
Display all account collections on WordPress

## Description
Same as for Dapp : 
Display all collections owned by an account
and where account has at least one NFT
moreover add the default mintable collection
(for the specific blockchain selected)

## Tests
To test on https://www.kredeum.org

> On Wordpress, if the user go on settings page before to go to the embeded dapp's page, the mintables collections doesn't display.
> 
> it's because the collections "supports" and "otherMetadatas" are only updated when the collections have been displayed once in "collection.svelte" component
> 
> So in the Dapp we begin to display in collection selector, all the collections (in collectionList.svelte => collection.svelte line.30), that update the supports and metadatas, and then when we open the mint modal, or when we go on settings page, the mintables collections are filtred
> 
> but if we go on wordpress plugin settings page before to go on embed dapp, we begin to try to display mintable collection before to update the collections datas.
> 
> Implication for other issue :
> If we want to  import a mint button in an html page, we'll have the same pb because when we'll display the mint modal, the collection selector will be displayed for the first time on the page, surching for mintable collections, but the supports and metadatas won't be updated to determine if the collections are mintable.

**Comment by zapaz** [comment]
fixed
