### ISSUE TITLE
TokenID error at end of mint

### ISSUE THREAD

**Issue by dlaxcess** [Kredeum/kredeum#252]
![Capture d’écran de 2022-08-05 20-52-06](https://user-images.githubusercontent.com/35979307/183143844-092e2959-c7b8-437f-a211-dea7b07635ce.png)

in "_mintTokenID" function (lib/knft-mint.ts l. 24), when we console.log "txReceipt.logs[0]" theres no "args" entry.
So "tokenID" is undefined.

So it causes error at the end of the mint. Despite this, the nft seems to be minted all the same...

**Comment by zapaz** [comment]
solved
