### ISSUE TITLE
Automarket

### ISSUE THREAD

**Issue by dlaxcess** [Kredeum/kredeum#272]
MANDATORY FOR MERGING :
- [x] add default mint price info in mint modal
- [x] add Price display in Nft details
- [x] add sell button ( Approve & setPrice => refresh after setting price )
- [x] add buy button in Nft details if not owner
- [x] add burn button on Nft detail page ( remove burned nft from store and local storage after burn )
- [x] add Transfer to addresse dEaD if burn function not defined in nft collection
- [x] Disable Transfer button when not effective
- [x] Get Price and royalties infos when not owner to permit buy function working ( with hash of the nft in url on first load nft.collection had only chainId and address. if reloaded brother, nft.collection becomed full hydratated)
- [x] display sell button only on OpenNFTsV4 template
- [x] display "sell on OpenSea" button
- [x] refresh owner and buttons after buy
- [x] display royalty infos on nft mint modale
- [x] add royalty infos fields in collection create and clone collection with thoses params
- [x] add setApprovalForAll in NftSell & check Approval
- [x] add optional set default collection price or default royalty infos at collection creation
 
OPTIONAL FEATURES OR AFTER MERGING :
- [x] Refresh after transfer
- [x] Burn Nft buyed (owner of nft, not owner of collection)
- [x] make price component to filter Ether format
- [ ] make royalty percentage component to filter input from % => base point
- [ ] Listen Events after buy to refresh nfts of ex owner of a buyed nft
- [ ] integrate new models from Alex
- [ ] test OpenSea Approve / OpenNFTsV4 approve

**Comment by zapaz** [comment]
done
