### ISSUE TITLE
Error in line mode

### ISSUE THREAD

**Issue by zapaz** [Kredeum/kredeum#296]
While switching in line mode with some audio NFTs

![Capture d’écran 2022-11-03 à 11 32 55](https://user-images.githubusercontent.com/4560471/199699239-25b32994-de9c-454a-9d1c-b7abda761c8e.png)

**Comment by dlaxcess** [comment]
![Capture d’écran de 2022-11-03 11-58-47](https://user-images.githubusercontent.com/35979307/199704283-93d506bf-f11f-4cff-89f7-4fffacfca2bb.png)

**Comment by zapaz** [comment]
bug in erc1155 balanceOf call with addressZero ;-(

**Comment by zapaz** [comment]
first fix in v0.17.1

still have to redeploy a new OpenNFTsResolverV1.1
