### ISSUE TITLE
Price validation error

### ISSUE THREAD

**Issue by dlaxcess** [Kredeum/kredeum#327]
After mint in the modal, the Amount indicated for the seller is not correct.
![image](https://user-images.githubusercontent.com/35979307/232468425-5c0c189c-5f95-41f4-8d81-f3e23115f4fe.png)

When the modal has been reload, the price is correct.
![image](https://user-images.githubusercontent.com/35979307/232469093-f388fc32-85d0-4de1-940b-f5f66830a065.png)

But il Nft details, the price is turned to red while it is valid.
![image](https://user-images.githubusercontent.com/35979307/232468885-7e18f91c-4800-4e63-b8ad-a535f81f2738.png)

**Comment by zapaz** [comment]
@dlaxcess  can you detail the params you used ? price , % , etc...

**Comment by zapaz** [comment]
fixed
